/*
 * handler_state_machine.h
 *
 *  Created on: Jun 24, 2026
 *      Author: kenny
 */

#ifndef DY50_FINGERPRINT_DRIVER_FOR_STM32_INC_DY50_TYPES_STATE_MACHINE_H_
#define DY50_FINGERPRINT_DRIVER_FOR_STM32_INC_DY50_TYPES_STATE_MACHINE_H_

typedef enum
{
	DY50_STATUS_UNINITIALIZED = 0,
	DY50_STATUS_IDLE,
	DY50_STATUS_ENROLL_HANDLER,
	DY50_STATUS_SEARCH_FINGERPRINT,
	DY50_STATUS_DELETE_TEMPLATE,
	DY50_STATUS_MATCH_HANDLER,
}DY50_Status_t;

typedef enum
{
	DY50_CMD_DMA_STATUS_IDLE,
	DY50_CMD_DMA_STATUS_SEND,
	DY50_CMD_DMA_STATUS_WAITING,
}DY50_Command_DMA_Status_t;

typedef enum
{
	DY50_GENCHAR_STATUS_IDLE,
	DY50_GENCHAR_STATUS_GET_IMAGE,
	DY50_GENCHAR_STATUS_GEN_CHAR,
}DY50_GenerateChar_Status_t;

typedef enum
{
	DY50_INIT_DEFINE_PARAMS = 0,
	DY50_INIT_READ_SYSTEM_PARAMS,
	DY50_INIT_VERIFY_PASSWORD,
	DY50_INIT_READ_INDEX_TABLE,
	DY50_INIT_COMPLETE,
	DY50_INIT_ERROR,
}DY50_Init_State;

typedef enum
{
	DY50_ENROLL_STATE_IDLE = 0,
	DY50_ENROLL_STATE_WRITE_BUFFER1,
	DY50_ENROLL_STATE_WRITE_BUFFER2,
	DY50_ENROLL_STATE_WRITE_BUFFER3,
	DY50_ENROLL_STATE_WRITE_BUFFER4,
	DY50_ENROLL_STATE_COMPLETE,
	DY50_ENROLL_STATE_WAITING_RESPONSE,

	DY50_ENROLL_ERROR_TIMEOUT = 100,
}DY50_EnrollState_t;

typedef enum
{
	DY50_ENROLL_HANDLER_STATE_IDLE = 0,
	DY50_ENROLL_HANDLER_CMD_ENROLL,
	DY50_ENROLL_HANDLER_CMD_REG_MODEL,
	DY50_ENROLL_HANDLER_CMD_STORE_CHAR,
	DY50_ENROLL_HANDLER_STATE_INITIALIZED,
}DY50_Enroll_Handler_State_t;

typedef enum
{
	DY50_SEARCH_STATE_IDLE = 0,
	DY50_SEARCH_STATE_CMD_GENCHAR,
	DY50_SEARCH_STATE_CMD_SEARCH,
	DY50_SEARCH_STATE_WAITING_RESPONSE,
	DY50_SEARCH_STATE_COMPLETED,

}DY50_SearchState_t;

typedef enum
{
	DY50_MATCH_STATE_IDLE = 0,
	DY50_MATCH_STATE_CMD_GENCHAR,
	DY50_MATCH_STATE_CMD_LOADCHAR,
	DY50_MATCH_STATE_CMD_MATCH,
}DY50_MatchStateHandler_t;

#endif /* DY50_FINGERPRINT_DRIVER_FOR_STM32_INC_DY50_TYPES_STATE_MACHINE_H_ */
